module Items

open Yaku
open Types

let allItems : Item list = [
  { name = "Tanyao"; description = "Grants +1 Yaku (score multiplier) if your hand has no 1 or 9 tiles."; rarity = Common; triggers = [YakuTrigger]; condition = ByRawHand tanyaopRaw; effect = (fun _ _ -> [ItemEffect.Yaku 1u]); cost = 150 }
  { name = "Pinfu"; description = "Grants +1 Yaku (score multiplier) if your hand consists of four sequences (e.g. 2-3-4) and a pair, and you were waiting to complete a sequence."; rarity = Common; triggers = [YakuTrigger]; condition = ByParsedHand pinfup; effect = (fun _ _ -> [ItemEffect.Yaku 1u]); cost = 150 }
  { name = "Iipeikou"; description = "Grants +1 Yaku (score multiplier) if your hand contains two identical sequences (e.g. two 2-3-4 sets)."; rarity = Common; triggers = [YakuTrigger]; condition = ByParsedHand iipeikoup; effect = (fun _ _ -> [ItemEffect.Yaku 1u]); cost = 100 }
  { name = "Ryanpeikou"; description = "Grants +3 Yaku (score multipliers) if your hand contains two sets of identical sequences."; rarity = Uncommon; triggers = [YakuTrigger]; condition = ByParsedHand ryanpeikoup; effect = (fun _ _ -> [ItemEffect.Yaku 3u]); cost = 75 }
  { name = "Ittsu"; description = "Grants +2 Yaku (score multipliers) if your hand contains three sequences forming a straight from 1 to 9 (1-2-3, 4-5-6, and 7-8-9)."; rarity = Uncommon; triggers = [YakuTrigger]; condition = ByParsedHand ittsup; effect = (fun _ _ -> [ItemEffect.Yaku 2u]); cost = 75 }
//   { name = "Toitoihou"; description = "Grants +2 Yaku (score multipliers) if your hand consists entirely of four triplets (or quads) and a pair, with no sequences."; rarity = Common; triggers = [YakuTrigger]; condition = ByParsedHand toitoihoup; effect = (fun _ _ -> [ItemEffect.Yaku 2u]); cost = 50 }
  { name = "Sanankou"; description = "Grants +2 Yaku (score multipliers) if your hand contains three concealed triplets (drawn by yourself, not stolen)."; rarity = Uncommon; triggers = [YakuTrigger]; condition = ByParsedHand sanankoup; effect = (fun _ _ -> [ItemEffect.Yaku 2u]); cost = 50 }
  { name = "Sankantsu"; description = "Grants +2 Yaku (score multipliers) if your hand contains three quads (four of a kind)."; rarity = Uncommon; triggers = [YakuTrigger]; condition = ByParsedHand sankantsup; effect = (fun _ _ -> [ItemEffect.Yaku 2u]); cost = 50 }
  { name = "Chitoitsu"; description = "Grants +2 Yaku (score multipliers) if your hand consists of exactly seven distinct pairs."; rarity = Uncommon; triggers = [YakuTrigger]; condition = ByParsedHand chitoitsup; effect = (fun _ _ -> [ItemEffect.Yaku 2u]); cost = 50 }
//   { name = "Chanta"; description = "Grants +2 Yaku (score multipliers) if every set and the pair in your hand contains at least one terminal (1 or 9) tile."; rarity = Common; triggers = [YakuTrigger]; condition = ByParsedHand chantap; effect = (fun _ _ -> [ItemEffect.Yaku 2u]); cost = 50 }
//   { name = "Junchan"; description = "Grants +3 Yaku (score multipliers) if every set and the pair in your hand contains at least one terminal (1 or 9) tile."; rarity = Common; triggers = [YakuTrigger]; condition = ByParsedHand junchanp; effect = (fun _ _ -> [ItemEffect.Yaku 3u]); cost = 50 }
//   { name = "Chinitsu"; description = "Grants +6 Yaku (score multipliers) unconditionally since all tiles in this game belong to the same suit."; rarity = Common; triggers = [YakuTrigger]; condition = Always; effect = (fun _ _ -> [ItemEffect.Yaku 6u]); cost = 50 }
  { name = "Suuankou"; description = "Grants +13 Yaku (massive score multiplier) if your hand contains four concealed triplets (drawn by yourself)."; rarity = Rare; triggers = [YakuTrigger]; condition = ByParsedHand suuankoup; effect = (fun _ _ -> [ItemEffect.Yaku 13u]); cost = 50 }
  { name = "Sukantsu"; description = "Grants +13 Yaku (massive score multiplier) if your hand contains four quads (four of a kind)."; rarity = Rare; triggers = [YakuTrigger]; condition = ByParsedHand sukantsup; effect = (fun _ _ -> [ItemEffect.Yaku 13u]); cost = 50 }
//   { name = "Chinroutou"; description = "Grants +13 Yaku (massive score multiplier) if your hand is composed entirely of 1s and 9s."; rarity = Common; triggers = [YakuTrigger]; condition = ByRawHand chinroutoupRaw; effect = (fun _ _ -> [ItemEffect.Yaku 13u]); cost = 50 }
//   { name = "Ryuuiisou"; description = "Grants +13 Yaku (massive score multiplier) if your hand is composed entirely of 2, 3, 4, 6, and 8 tiles."; rarity = Common; triggers = [YakuTrigger]; condition = ByRawHand ryuuiisoupRaw; effect = (fun _ _ -> [ItemEffect.Yaku 13u]); cost = 50 }
//   { name = "ChuurenPoutou"; description = "Grants +13 Yaku (massive score multiplier) if your hand consists of three 1s, three 9s, and one of every other number (1112345678999) plus one extra tile."; rarity = Common; triggers = [YakuTrigger]; condition = ByParsedHand chuurenPoutoup; effect = (fun _ _ -> [ItemEffect.Yaku 13u]); cost = 50 }
  { name = "SuuankouTanki"; description = "Grants +26 Yaku (colossal score multiplier) if you complete four concealed triplets by drawing the final tile to form the pair."; rarity = Legendary; triggers = [YakuTrigger]; condition = ByParsedHand suuankouTankip; effect = (fun _ _ -> [ItemEffect.Yaku 26u]); cost = 50 }
//   { name = "JunseiChuurenPoutou"; description = "Grants +26 Yaku (colossal score multiplier) if you complete the exact 1112345678999 hand by drawing a matching tile."; rarity = Common; triggers = [YakuTrigger]; condition = ByParsedHand junseiChuurenPoutoup; effect = (fun _ _ -> [ItemEffect.Yaku 26u]); cost = 50 }
]
